### ISSUE TITLE
Allow Returning Sets or Lists from Functions

### ISSUE THREAD

**Issue by lab57** [OrangeX4/typst-sympy-calculator#1]
Currently, if I have something like
```
#let null = math.op("N")
'''typst-sympy-calculator
@func_mat()
def convert_null(mat):
    return sympy.Matrix(mat).nullspace()
'''
```
in my Typst file, this function called on something like `null(mat(1, 2; 2, 4))` will fail with 
`'list' object has no attribute 'subs'`
presumably because it expects the return object to be a sympy object with the .subs() method. It would be nice to have a way to return a list of sympy objects, and have it rendered as a set, for example in this case
`{ vec(2, -1) }`

**Comment by OrangeX4** [comment]
I'm sorry for replying so late. I've been quite busy lately and completely forgot about this matter until today.

It has been fixed now. You can reinstall it by using the command: `pip install typst-sympy-calculator==0.6.0`.
